public class topThreeFlights {

    /**
    * Prints the top flight options from the 2D array of flight information generated by FlightSearch.java
    * Precondition: flights is a 2D array of flight information, where each row represents one flight option. The format is correct as per FlightSearch.java
    * Postcondition: Information about the top flight options is printed to the console.

    * @param flights is a 2D array of flight information, where each row represents one flight option
    */
    public static void topThree(String[][] flights) {
        // Print all of the identified top flight options from the recieved 2D array
        System.out.println();
        System.out.println("________Top Flight Options________\n");
        System.out.println("Note: If flight shows \"$0 CAD\", the price is currently unavailable.\n \n");

        //Itrates for all of the flights in the 2D array
        for (String[] flight : flights) {

            //Prints based on the format given in FlightSearch.java
            System.out.println(flight[3] + " flight from " + flight[6] + "\n \n" + flight[0] + " Flight " + flight[1] + " for " + flight[4] + "\n"); 
            System.out.println("Info:\n \nPlane Type: " + flight[2]);
            System.out.println("Flight Time: " + flight[5]);
            System.out.println("Details: " + flight[7]);       
            System.out.println("\n__________________________________\n");
        }
    }

    /**
    * This method is an overload of topThree(String[][]) method and is called when the user does not want to have the top flight options printed.
    * 
    * Postcondition: Nothing is printed to the console, skipping the printing of the top flight options.
    */
    public static void topThree() {
        return;
    }

}
